spring:
  application:
    name: circuit-breaker-service
  boot:
    admin:
      client:
        url: http://localhost:8080 # Point to the Dashboard

server:
  port: 8081

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # We are providing metrics for the dashboard.
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default: # Esto aplica a todos los circuitos por defecto
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true
    instances:
      externalApiConfig:
        baseConfig: default
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
